### ISSUE TITLE
Add viewport offsets to external recommender

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#1861]
**Is your feature request related to a problem? Please describe.**
Add viewport offsets to external recommender so that the recommender knows where to predict.

**Describe the solution you'd like**
Add viewport begin/end to external recommender request.

**Todo**
- [x] Send viewport along
- [ ] Allow external recommender to respond the area in which it actually did predict or handle this on the INCEpTION side
- [ ] Report the predicted range to the recommender service
