### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2475]
**Describe the refactoring action**
Upgrade to Bootstrap 5.

**Expected benefit**
Use the latest and greatest.

**Additional context**
* https://github.com/l0rdn1kk0n/wicket-bootstrap/issues/902
* https://github.com/l0rdn1kk0n/wicket-bootstrap/tree/wicket-9.x-bootstrap-5.x

**Todo**

*AnnotationDetailPanel*
- [x]  placeholder before identifier link looks weird/small

*Search sidebar*
- [x] White text in result list headings is hard to read

*KB*
- [x]  buttons containing both image and label: label and image are too close together
- [x]  adding a string statement: textfield too squashed
- [x]  button and textfield next to each other (create concept) differ in size

*Monitoring Page*
- [x]  (on small screen) legend not fully visible

*Settings: Layers*
- [x] *Feature Details: Key Bindings* placeholder has the same too small look as on the *AnnotationDetailPanel* (see above)

*Dashboard*
- [x] The tags for annotation or curation in the recent activities are missing

**Comment by jcklie** [comment]
Login form is smaller
![image](https://user-images.githubusercontent.com/934600/131223685-5a196770-e4fa-401b-aa7c-e2e39c062cb2.png)

**Comment by jcklie** [comment]
Navbar is tighter

![image](https://user-images.githubusercontent.com/934600/131223697-95c0564f-eb57-4261-94f2-a842efe6c0c2.png)
![image](https://user-images.githubusercontent.com/934600/131223705-6f16763a-03d5-4a6b-b459-a68cc27921d9.png)

**Comment by jcklie** [comment]
I do not like the underline of links (and different font?) in the project list

![image](https://user-images.githubusercontent.com/934600/131223738-dc1fab1e-2caf-4aef-b3c1-8bef6a303037.png)
![image](https://user-images.githubusercontent.com/934600/131223741-d47a69ac-dc24-41f4-93fb-ae243a7b1f0b.png)
