### ISSUE TITLE
Multi-value string feature

### ISSUE THREAD

**Issue by reckart** [inception-project/inception#2862]
**Is your feature request related to a problem? Please describe.**
Sometimes, it would be nice to be able to assign multiple tags to a given feature. 

**Describe the solution you'd like**
The ability to assign multiple tags to an annotation in a single feature.

Not sure yet how to handle this in curation, recommenders or agreement.

**Describe alternatives you've considered**
Currently, the only way to multi-tag is essentially to stack. However, when the annotation should take part in relations or links, then stacking is not such a nice option.

**Todo**

- [x] Added multi-value string-feature support
- [x] Feature flag
- [x] Multi-value string editor which works like a multi-value auto-complete or combo-box
- [x] Description tooltips when overing over items in the dropdown menu
- [x] CasDiff supports multi-value string (string-array) and treats it as an unordered set of values
- [x] Handle multi-value strings in agreement
- [x] Curation: Can click on annotation carrying multi-value string feature and feature value is merged
- [x] Curation: shows differences when multi-value feature differs
- [x] Recommenders: Basic support in string-matching recommender
- [x] Support multi-value string features on UIMA type system import
- [x] Documentation
