### ISSUE TITLE
Add LAPPS Grid external recommender support

### ISSUE THREAD

**Issue by jcklie** [inception-project/inception#950]
**Is your feature request related to a problem? Please describe.**
Right now, the internal recomenders in INCEpTION suffer from cold start as they are trained from scratch. It would be therefore nice to have more models that are pretrained. LAPPS grid offers a wide range of models exposed as a web service which could be integrated.

**Describe the solution you'd like**
Add a kind of external recommender that can query LAPPS grid services.

**Todos**
* [x] Add recommender connecting to LAPPS services
* [x] Add unit tests against the LAPPS services
* [x] Curate list of recommenders that work
* [x] Write integration test
* [x] Write documentation
* [x] Remove feature toggle and turn it always on
